import { useEffect, useMemo, useState } from "react";
import { api } from "./api";
import AuthCard from "./components/AuthCard";
import Modal from "./components/Modal";

const money = value => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(value || 0);
const when = value => new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
const requestKey = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`;

function Header({ user, logout }) {
  return <header className="topbar"><a className="brand" href="/"><span className="brand-mark">F</span><span>Flow<b>Ledger</b></span></a><span className="demo-label">BANKING TRANSACTION DEMO</span>{user && <div className="user-menu"><span className="user-avatar">{user.name[0]}</span><span><strong>{user.name}</strong><small>{user.role === "ADMIN" ? "Administrator" : "Customer"}</small></span><button className="button quiet" onClick={logout}>Sign out</button></div>}</header>;
}

function Statement({ entries }) {
  const [filter, setFilter] = useState("ALL");
  const rows = useMemo(() => entries.filter(entry => filter === "ALL" || entry.entryType === filter), [entries, filter]);
  const details = entry => {
    if (entry.operation === "OPENING_DEPOSIT") return "Opening cash deposit";
    if (entry.operation === "CASH_DEPOSIT") return "Cash deposit at counter";
    if (entry.operation === "CASH_WITHDRAWAL") return "Cash withdrawal at counter";
    return entry.entryType === "DEBIT" ? `Online transfer to ${entry.toAccount?.accountNumber || "recipient"}` : `Online transfer from ${entry.fromAccount?.accountNumber || "sender"}`;
  };
  return <section className="card table-card"><div className="section-title"><div><span className="eyebrow">Account statement</span><h2>Transaction history</h2></div><select value={filter} onChange={event => setFilter(event.target.value)}><option value="ALL">All activity</option><option value="CREDIT">Credits</option><option value="DEBIT">Debits</option></select></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Details</th><th>Debit</th><th>Credit</th><th>Balance</th><th>Status</th></tr></thead><tbody>{rows.length ? rows.map(entry => { const debit = entry.entryType === "DEBIT"; return <tr key={entry._id}><td>{when(entry.statementDate || entry.createdAt)}</td><td>{details(entry)}</td><td className="amount debit-text">{debit ? money(entry.amount) : "—"}</td><td className="amount credit-text">{debit ? "—" : money(entry.amount)}</td><td className="amount">{money(entry.balanceAfter)}</td><td><span className="pill neutral">{entry.status}</span></td></tr>; }) : <tr><td colSpan="6" className="empty">No transactions match this filter.</td></tr>}</tbody></table></div></section>;
}

function Customer({ user, token, notify }) {
  const [account, setAccount] = useState(); const [entries, setEntries] = useState([]); const [dialog, setDialog] = useState(); const [loading, setLoading] = useState(true);
  const refresh = async () => { setLoading(true); try { const [accounts, history] = await Promise.all([api("/api/accounts", { token }), api("/api/transactions", { token })]); setAccount(accounts.accounts[0]); setEntries(history.transactions || []); } catch (error) { notify(error.message, "error"); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  const transfer = async event => { event.preventDefault(); const values = new FormData(event.currentTarget); try { await api("/api/transactions", { method: "POST", token, body: { fromAccount: account.accountNumber, toAccount: values.get("toAccount"), amount: Number(values.get("amount")), transactionPin: values.get("pin"), idempotencyKey: requestKey() } }); notify("Transfer completed."); setDialog(); refresh(); } catch (error) { notify(error.message, "error"); } };
  const pin = async event => { event.preventDefault(); try { await api("/api/auth/set-pin", { method: "POST", token, body: { pin: new FormData(event.currentTarget).get("pin") } }); user.hasPin = true; localStorage.setItem("ledger_user", JSON.stringify(user)); notify("Transaction PIN saved."); setDialog(); } catch (error) { notify(error.message, "error"); } };
  if (loading) return <main className="page"><p className="loading">Loading your account…</p></main>;
  if (!account) return <main className="page"><section className="card empty-state"><h1>Your account is being prepared</h1><p>A cashier needs to complete your onboarding first.</p></section></main>;
  return <main className="page"><div className="welcome"><div><span className="eyebrow">Customer dashboard</span><h1>Hello, {user.name.split(" ")[0]}.</h1><p>Your available balance and statement are shown below.</p></div><button className="button quiet" onClick={refresh}>Refresh</button></div><section className="account-grid"><article className="balance-card"><span>Available balance</span><strong>{money(account.balance)}</strong><div className="account-id"><span>{account.accountNumber}</span><button className="copy" onClick={() => navigator.clipboard.writeText(account.accountNumber).then(() => notify("Account number copied."))}>Copy</button></div><small>{account.currency} · {account.status}</small></article><article className="card security-card"><span className="eyebrow">Transfer security</span><h2>{user.hasPin ? "PIN protection enabled" : "Set your transaction PIN"}</h2><p>{user.hasPin ? "Every online transfer requires your four-digit PIN." : "Set a PIN before making an online transfer."}</p><button className="button secondary" onClick={() => setDialog("pin")}>{user.hasPin ? "Change PIN" : "Set PIN"}</button></article></section><section className="actions"><button className="button primary" onClick={() => setDialog("transfer")}>Send money</button><p>Deposits and withdrawals are recorded by a cashier.</p></section><Statement entries={entries} />{dialog === "transfer" && <Modal title="Send money" onClose={() => setDialog()}><form className="form" onSubmit={transfer}><label>Recipient account number<input name="toAccount" required /></label><label>Amount (₹)<input name="amount" type="number" min="1" step="0.01" required /></label><label>Transaction PIN<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{4}" maxLength="4" required /></label><button className="button primary">Authorize transfer</button></form></Modal>}{dialog === "pin" && <Modal title="Set transaction PIN" onClose={() => setDialog()}><form className="form" onSubmit={pin}><label>Four-digit PIN<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{4}" maxLength="4" required /></label><button className="button primary">Save PIN</button></form></Modal>}</main>;
}

function Admin({ token, notify }) {
  const [stats, setStats] = useState({}); const [accounts, setAccounts] = useState([]); const [transactions, setTransactions] = useState([]);
  const refresh = async () => { try { const [summary, registry, audit] = await Promise.all([api("/api/admin/stats", { token }), api("/api/admin/accounts", { token }), api("/api/admin/transactions", { token })]); setStats(summary); setAccounts(registry.accounts || []); setTransactions(audit.transactions || []); } catch (error) { notify(error.message, "error"); } };
  useEffect(() => { refresh(); }, []);
  const onboard = async event => { event.preventDefault(); const form = event.currentTarget; try { const result = await api("/api/admin/onboard-customer", { method: "POST", token, body: Object.fromEntries(new FormData(form)) }); form.reset(); notify(`Account ${result.customer.accountNumber} created.`); refresh(); } catch (error) { notify(error.message, "error"); } };
  const cash = async (event, path) => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); try { const result = await api(path, { method: "POST", token, body: { accountNumber: values.get("accountNumber"), amount: Number(values.get("amount")) } }); form.reset(); notify(result.message); refresh(); } catch (error) { notify(error.message, "error"); } };
  return <main className="page"><div className="welcome"><div><span className="eyebrow">Administrator workspace</span><h1>Operations & audit</h1><p>Online and cashier transactions are stored in MongoDB.</p></div><button className="button quiet" onClick={refresh}>Refresh data</button></div><section className="stats-grid"><article className="stat green"><span>Cash reserve</span><strong>{money(stats.totalReserve)}</strong></article><article className="stat"><span>Customer accounts</span><strong>{stats.accountCount || 0}</strong></article><article className="stat purple"><span>Transactions</span><strong>{stats.transactionCount || 0}</strong></article></section><section className="operations"><form className="card form" onSubmit={onboard}><div><span className="eyebrow">New customer</span><h2>Onboard customer</h2></div><label>Full name<input name="name" required /></label><label>Email<input name="email" type="email" required /></label><label>Temporary password<input name="password" type="password" minLength="6" required /></label><label>Initial cash deposit (₹)<input name="initialDeposit" type="number" min="0" defaultValue="0" /></label><button className="button primary">Create account</button></form><section className="card"><span className="eyebrow">Offline cashier transaction</span><h2>Cash counter</h2><form className="form compact" onSubmit={event => cash(event, "/api/admin/cash-deposit")}><label>Account number<input name="accountNumber" required /></label><label>Amount (₹)<input name="amount" type="number" min="1" required /></label><button className="button secondary">Record cash deposit</button></form><form className="form compact divider" onSubmit={event => cash(event, "/api/admin/cash-withdraw")}><label>Account number<input name="accountNumber" required /></label><label>Amount (₹)<input name="amount" type="number" min="1" required /></label><button className="button danger">Record cash withdrawal</button></form></section></section><Audit title="Full audit trail" transactions={transactions} /><Audit title="Customer accounts" transactions={accounts} accounts /></main>;
}

function Audit({ title, transactions, accounts }) { return <section className="card table-card"><div className="section-title"><div><span className="eyebrow">{title}</span><h2>{accounts ? "Accounts" : "Online & offline transactions"}</h2></div></div><div className="table-wrap">{accounts ? <table><thead><tr><th>Account</th><th>Customer</th><th>Email</th><th>Balance</th><th>Status</th></tr></thead><tbody>{transactions.map(item => <tr key={item._id}><td className="mono">{item.accountNumber}</td><td>{item.customerName}</td><td>{item.customerEmail}</td><td className="amount">{money(item.balance)}</td><td>{item.status}</td></tr>)}</tbody></table> : <table><thead><tr><th>Date</th><th>Channel</th><th>Operation</th><th>From</th><th>To</th><th>Amount</th><th>Status</th></tr></thead><tbody>{transactions.map(item => <tr key={item._id}><td>{when(item.createdAt)}</td><td>{item.channel}</td><td>{item.operation}</td><td className="mono">{item.fromAccount?.accountNumber}</td><td className="mono">{item.toAccount?.accountNumber}</td><td className="amount">{money(item.amount)}</td><td>{item.status}</td></tr>)}</tbody></table>}</div></section>; }

export default function App() { const [user, setUser] = useState(() => JSON.parse(localStorage.getItem("ledger_user") || "null")); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(); const notify = (message, type = "success") => { setNotice({ message, type }); setTimeout(() => setNotice(), 4000); }; const login = async (values, portal) => { setBusy(true); try { const result = await api("/api/auth/login", { method: "POST", body: values }); if (result.user.role !== portal) throw new Error(portal === "ADMIN" ? "These are not administrator credentials." : "Please use Customer login for this account."); const next = { ...result.user, token: result.token }; localStorage.setItem("ledger_user", JSON.stringify(next)); setUser(next); } catch (error) { notify(error.message, "error"); } finally { setBusy(false); } }; const logout = () => { localStorage.removeItem("ledger_user"); setUser(); }; return <><Header user={user} logout={logout} />{user ? user.role === "ADMIN" ? <Admin token={user.token} notify={notify} /> : <Customer user={user} token={user.token} notify={notify} /> : <AuthCard onLogin={login} busy={busy} />}{notice && <div className={`toast ${notice.type}`}>{notice.message}</div>}</>; }
